const MAINCHAIN_GENESIS_BLOCK_REWARD = 5000000000;
const MAINCHAIN_BLOCK_TIME = 600000;

const MAINCHAIN_DIFFICULTY_TUNING_INTERVAL=1000;
const MAINCHAIN_REWARD_TUNING_INTERVAL=100000;
const MAINCHAIN_BLOCK_MAX_SEIZE=1024*1024;
const MAINCHAIN_MESSAGE_MAX_SEIZE=50*1024*1024;
const TRANSACTION_VERSION=1;
module.exports = {
    MAINCHAIN_GENESIS_BLOCK_REWARD,
    MAINCHAIN_BLOCK_TIME,
    MAINCHAIN_DIFFICULTY_TUNING_INTERVAL,
    MAINCHAIN_REWARD_TUNING_INTERVAL,
    MAINCHAIN_BLOCK_MAX_SEIZE,
    MAINCHAIN_MESSAGE_MAX_SEIZE,
    TRANSACTION_VERSION
};